
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'AAF35586F16F71C8D6034AAF4C600B4A'
    
_lr_action_items = {'DECIMAL_LITERAL':([13,19,21,22,24,25,30,40,65,68,],[21,21,-21,-19,21,-20,21,21,66,21,]),'WORD':([1,8,13,19,21,22,24,25,30,40,68,],[4,15,22,22,-21,-19,22,-20,22,22,22,]),'NETWORK':([0,],[1,]),'PROBABILITY':([2,7,9,10,12,20,28,49,56,],[5,-14,-13,5,-25,-27,-26,-33,-35,]),')':([21,22,23,24,25,32,54,],[-21,-19,31,-5,-20,-6,63,]),'(':([5,26,33,37,38,39,41,59,61,62,64,],[13,40,-18,40,-16,-15,-17,-24,-31,-30,-32,]),'DEFAULTVALUE':([26,33,37,38,39,41,59,61,62,64,],[35,-18,35,-16,-15,-17,-24,-31,-30,-32,]),']':([66,],[67,]),'TABLEVALUES':([26,33,37,38,39,41,59,61,62,64,],[42,-18,42,-16,-15,-17,-24,-31,-30,-32,]),'DISCRETE':([46,],[57,]),'[':([57,],[65,]),'VARIABLE':([2,7,9,10,12,20,28,49,56,],[8,-14,-13,8,-25,-27,-26,-33,-35,]),'VARIABLETYPE':([27,44,45,47,59,71,],[46,-22,-23,46,-24,-34,]),'{':([4,14,15,31,67,],[11,26,27,-28,68,]),'PROPERTY':([11,18,26,27,33,37,38,39,41,44,45,47,59,61,62,64,71,],[19,19,19,19,-18,19,-16,-15,-17,-22,-23,19,-24,-31,-30,-32,-34,]),'}':([11,17,18,21,22,24,25,29,32,33,34,37,38,39,41,43,44,45,47,53,58,59,61,62,64,69,71,],[20,28,-9,-21,-19,-5,-20,-10,-6,-18,49,-7,-16,-15,-17,56,-22,-23,-11,-8,-12,-24,-31,-30,-32,70,-34,]),';':([21,22,24,25,32,48,50,51,52,55,60,70,],[-21,-19,-5,-20,-6,59,-3,61,62,64,-4,71,]),'FLOATING_POINT_LITERAL':([13,19,21,22,24,25,30,35,36,40,42,50,63,68,],[25,25,-21,-19,25,-20,25,50,50,25,50,50,-29,25,]),'$end':([3,6,7,9,10,16,49,56,],[0,-36,-14,-13,-1,-2,-33,-35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'probability_values_list':([26,37,],[36,36,]),'probability_default_entry':([26,37,],[41,41,]),'variable_declaration':([2,10,],[9,9,]),'probability_table':([26,37,],[33,33,]),'property_list':([11,18,],[17,29,]),'network_declaration':([0,],[2,]),'variable_content':([27,47,],[43,58,]),'property_string':([11,18,26,27,37,47,],[18,18,39,44,39,44,]),'floating_point_list':([35,36,42,50,],[51,52,55,60,]),'probability_content':([26,37,],[34,53,]),'variable_content_item':([27,47,],[47,47,]),'blocks_list':([2,10,],[6,16,]),'compilation_unit':([0,],[3,]),'probability_declaration':([2,10,],[7,7,]),'probability_entry':([26,37,],[38,38,]),'variable_discrete':([27,47,],[45,45,]),'probability_variables_list':([5,],[14,]),'network_content':([4,],[12,]),'list':([13,24,30,40,68,],[23,32,48,54,69,]),'value':([13,19,24,30,40,68,],[24,30,24,24,24,24,]),'probability_content_item':([26,37,],[37,37,]),'block':([2,10,],[10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> compilation_unit","S'",1,None,None,None),
  ('blocks_list -> block','blocks_list',1,'p_blocks_list','bif_yacc.py',10),
  ('blocks_list -> block blocks_list','blocks_list',2,'p_blocks_list','bif_yacc.py',11),
  ('floating_point_list -> FLOATING_POINT_LITERAL','floating_point_list',1,'p_floating_point_list','bif_yacc.py',10),
  ('floating_point_list -> FLOATING_POINT_LITERAL floating_point_list','floating_point_list',2,'p_floating_point_list','bif_yacc.py',11),
  ('list -> value','list',1,'p_list','bif_yacc.py',10),
  ('list -> value list','list',2,'p_list','bif_yacc.py',11),
  ('probability_content -> probability_content_item','probability_content',1,'p_probability_content','bif_yacc.py',10),
  ('probability_content -> probability_content_item probability_content','probability_content',2,'p_probability_content','bif_yacc.py',11),
  ('property_list -> property_string','property_list',1,'p_property_list','bif_yacc.py',10),
  ('property_list -> property_string property_list','property_list',2,'p_property_list','bif_yacc.py',11),
  ('variable_content -> variable_content_item','variable_content',1,'p_variable_content','bif_yacc.py',10),
  ('variable_content -> variable_content_item variable_content','variable_content',2,'p_variable_content','bif_yacc.py',11),
  ('block -> variable_declaration','block',1,'p_block','bif_yacc.py',27),
  ('block -> probability_declaration','block',1,'p_block','bif_yacc.py',28),
  ('probability_content_item -> property_string','probability_content_item',1,'p_probability_content_item','bif_yacc.py',27),
  ('probability_content_item -> probability_entry','probability_content_item',1,'p_probability_content_item','bif_yacc.py',28),
  ('probability_content_item -> probability_default_entry','probability_content_item',1,'p_probability_content_item','bif_yacc.py',29),
  ('probability_content_item -> probability_table','probability_content_item',1,'p_probability_content_item','bif_yacc.py',30),
  ('value -> WORD','value',1,'p_value','bif_yacc.py',27),
  ('value -> FLOATING_POINT_LITERAL','value',1,'p_value','bif_yacc.py',28),
  ('value -> DECIMAL_LITERAL','value',1,'p_value','bif_yacc.py',29),
  ('variable_content_item -> property_string','variable_content_item',1,'p_variable_content_item','bif_yacc.py',27),
  ('variable_content_item -> variable_discrete','variable_content_item',1,'p_variable_content_item','bif_yacc.py',28),
  ('property_string -> PROPERTY value list ;','property_string',4,'p_property_string','bif_yacc.py',54),
  ('network_declaration -> NETWORK WORD network_content','network_declaration',3,'p_network_declaration','bif_yacc.py',59),
  ('network_content -> { property_list }','network_content',3,'p_network_content','bif_yacc.py',64),
  ('network_content -> { }','network_content',2,'p_network_content','bif_yacc.py',65),
  ('probability_variables_list -> ( list )','probability_variables_list',3,'p_probability_variables_list','bif_yacc.py',73),
  ('probability_values_list -> ( list )','probability_values_list',3,'p_probability_values_list','bif_yacc.py',78),
  ('probability_entry -> probability_values_list floating_point_list ;','probability_entry',3,'p_probability_entry','bif_yacc.py',83),
  ('probability_default_entry -> DEFAULTVALUE floating_point_list ;','probability_default_entry',3,'p_probability_default_entry','bif_yacc.py',88),
  ('probability_table -> TABLEVALUES floating_point_list ;','probability_table',3,'p_probability_table','bif_yacc.py',93),
  ('probability_declaration -> PROBABILITY probability_variables_list { probability_content }','probability_declaration',5,'p_probability_declaration','bif_yacc.py',97),
  ('variable_discrete -> VARIABLETYPE DISCRETE [ DECIMAL_LITERAL ] { list } ;','variable_discrete',9,'p_variable_discrete','bif_yacc.py',102),
  ('variable_declaration -> VARIABLE WORD { variable_content }','variable_declaration',5,'p_variable_declaration','bif_yacc.py',107),
  ('compilation_unit -> network_declaration blocks_list','compilation_unit',2,'p_compilation_unit','bif_yacc.py',112),
]
